# install general packages

- name: install_pkgs | Install Packages
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - ansible
    - bzr
    - cifs-utils
    - ctags
    - curl
    - dh-golang
    - dnsutils
    - docker-ce
    - fonts-firacode
    - fonts-symbola
    - ftp
    - git
    - htop
    - jq
    - libfuse-dev
    - make
    - mosh
    - mumble
    - neovim-qt
    - nginx
    - nodejs
    - pandoc
    - polari
    - python-netaddr
    - python-pip
    - rsync
    - samba
    - silversearcher-ag
    - sl
    - sshfs
    - sudo
    - syncthing
    - tarsnap
    - tig
    - tmux
    - tree
    - vim-gtk3
    - vlc
    - zsh
   # these will likely move to backports
    - docker-compose
    - flatpak
    - golang
    - neovim
    - neovim-runtime
    - remmina

# pip packages

- name: install_pkgs | yq - YAML Query
  pip:
    name: "{{item}}"
  with_items:
    - yq
