- name: pkg_repos | Install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest

- name: pkg_repos | Setup Repository Keys
  apt_key:
    url: "{{item}}"
    state: present
  with_items:
    - https://download.docker.com/linux/debian/gpg
    - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - https://syncthing.net/release-key.txt
    - https://www.virtualbox.org/download/oracle_vbox_2016.asc
    - https://www.virtualbox.org/download/oracle_vbox.asc

- name: pkg_repos | Setup Repositories
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items:
    - "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
    - "deb https://deb.nodesource.com/node_10.x buster main"
    - "deb-src https://deb.nodesource.com/node_10.x buster main"
    - "deb https://apt.syncthing.net/ syncthing stable"
    - "deb http://download.virtualbox.org/virtualbox/debian buster contrib"
