- name: pkg_repos | Install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest

- name: pkg_repos | Setup Repository Keys
  apt_key:
    url: "{{item}}"
    state: present
  with_items:
    - https://download.docker.com/linux/debian/gpg
    - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - https://syncthing.net/release-key.txt

- name: pkg_repos | Setup Repositories
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items:
    - "deb http://security.debian.org/debian-security buster/updates contrib non-free"
    - "deb-src http://security.debian.org/debian-security buster/updates contrib non-free"
    - "deb http://ftp.us.debian.org/debian buster contrib non-free"
    - "deb-src http://ftp.us.debian.org/debian buster contrib non-free"
    - "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
    - "deb https://deb.nodesource.com/node_10.x buster main"
    - "deb-src https://deb.nodesource.com/node_10.x buster main"
    - "deb https://apt.syncthing.net/ syncthing stable"
