# install general packages

- name: install_pkgs | Install Packages
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - ansible
    - arc-theme
    - bzr
    - cifs-utils
    - ctags
    - curl
    - dh-golang
    - dnsutils
    - docker-ce
    - ffmpeg
    - firmware-iwlwifi
    - fonts-firacode
    - fonts-symbola
    - ftp
    - git
    - gnome-boxes
    - gnome-tweak-tool
    - htop
    - jq
    - libfuse-dev
    - libuv1-dev
    - llvm
    - make
    - mosh
    - mumble
    - neovim-qt
    - nginx
    - nodejs
    - pandoc
    - polari
    - python-netaddr
    - python-pip
    - qtcreator
    - qt5-default
    - redshift-gtk
    - rsync
    - samba
    - silversearcher-ag
    - sl
    - sshfs
    - sudo
    - syncthing
    - tarsnap
    - tig
    - tmux
    - tree
    - vim-gtk3
    - virtualbox-5.2
    - vlc
    - zfs-dkms
    - zfsutils-linux
    - zsh

- name: install_pkgs | Install Backports Packages
  apt:
    name: "{{item}}"
    state: latest
    default_release: stretch-backports
  with_items:
    - docker-compose
    - flatpak
    - golang
    - neovim
    - neovim-runtime
    - remmina

# pip packages

- name: install_pkgs | yq - YAML Query
  pip:
    name: "{{item}}"
  with_items:
    - yq
