---
  - hosts: no-de
    tasks:
    - include: 'no-de/no-de.yml'

  - hosts: cpp-dev
    tasks:
    - include: 'cpp-dev/cpp-dev.yml'

  - hosts: icecc-scheduler
    tasks:
    - include: 'icecc-node/icecc-node.yml'

  - hosts: icecc-node
    tasks:
    - include: 'icecc-node/icecc-node.yml'

  - hosts: workstations
    tasks:
    - include: 'workstation/workstation.yml'

  - hosts: openvpn_servers
    tasks:
    - include: 'openvpn/openvpn.yml'

  - hosts: plex_servers
    tasks:
    - include: 'plex_server/plex_server.yml'
